services:
  - type: web
    name: church-management-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: church-db
          property: connectionString

databases:
  - name: church-db
    databaseName: church_db
    user: church_user